import inquirer from 'inquirer';
import * as tmp from 'tmp';
import * as fs from 'fs';
import * as child_process from 'child_process';
import { getStagedDiff } from '../context/git';
import { getAntigravityContext } from '../context/antigravity';
import { getOpenAIClient, getModel } from '../ai/client';
import simpleGit from 'simple-git';

const git = simpleGit();

interface CommitOptions {
    tradeOffs?: boolean;
    aiAttribution?: boolean;
    dryRun?: boolean;
}

export async function generateCommitMessage(options: CommitOptions = { tradeOffs: true, aiAttribution: false }) {
    // 1. Get Staged Diff
    const diff = await getStagedDiff();
    if (!diff) {
        console.error('No staged changes found. Please stage files with "git add" first.');
        return;
    }

    // 2. Get AI Context
    const context = await getAntigravityContext();

    // 3. Construct Prompt
    let promptContext = '';
    if (context) {
        promptContext = `
ANTIGRAVITY CONTEXT:
Task Status:
${context.taskContent}

Implementation Plan:
${context.planContent}
`;
    } else {
        promptContext = 'No active AI session context found. Rely solely on the diff.';
    }

    // Adjust prompt based on options
    const tradeOffInstruction = options.tradeOffs !== false
        ? '4. If the Context mentions "User Review Required" or "Trade-offs", include that in the body.'
        : '4. Do NOT include a separate section for trade-offs.';

    const attributionInstruction = options.aiAttribution
        ? '5. Add a footer: "Generated by Antigravity CLI".'
        : '';

    const systemPrompt = `
You are a senior developer's assistant. Your goal is to write a semantic git commit message.
You have access to the code changes (DIFF) and the high-level intent/planning documents (CONTEXT).

Output Format:
<type>(<scope>): <subject>

<body>

<footer>

Rules:
1. Use the Context to understand *WHY* changes were made (Intent).
2. Use the Diff to understand *WHAT* changed (Implementation).
3. Be concise but descriptive. 
${tradeOffInstruction}
${attributionInstruction}
`;

    const userPrompt = `
CONTEXT:
${promptContext}

DIFF:
${diff}

Generate the commit message.
`;

    console.log('Generating commit message...');

    // 4. Call AI
    let commitMessage = '';
    try {
        const openai = getOpenAIClient();
        const completion = await openai.chat.completions.create({
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userPrompt }
            ],
            model: getModel(),
        });

        commitMessage = completion.choices[0].message.content || '';

    } catch (error: any) {
        console.error('Error generating commit message:', error.message);
        return;
    }

    if (options.dryRun) {
        console.log('\n--- Generated Commit Message (Dry Run) ---\n');
        console.log(commitMessage);
        return;
    }

    // 5. Interactive Loop
    while (true) {
        console.log('\n--- Draft Commit Message ---\n');
        console.log(commitMessage);
        console.log('\n----------------------------\n');

        const { action } = await inquirer.prompt([{
            type: 'list',
            name: 'action',
            message: 'What would you like to do?',
            choices: [
                { name: 'Commit (Run git commit)', value: 'commit' },
                { name: 'Edit (Open in Editor)', value: 'edit' },
                { name: 'Cancel', value: 'cancel' }
            ]
        }]);

        if (action === 'cancel') {
            console.log('Operation cancelled.');
            break;
        }

        if (action === 'commit') {
            try {
                await git.commit(commitMessage);
                console.log('Changes committed successfully!');
            } catch (err: any) {
                console.error('Failed to commit:', err.message);
            }
            break;
        }

        if (action === 'edit') {
            // Open editor
            const tmpObj = tmp.fileSync({ postfix: '.txt' });
            fs.writeFileSync(tmpObj.name, commitMessage);

            const editor = process.env.EDITOR || (process.platform === 'win32' ? 'notepad' : 'vi');

            try {
                console.log(`Opening ${editor}...`);
                child_process.execFileSync(editor, [tmpObj.name], { stdio: 'inherit' });
                commitMessage = fs.readFileSync(tmpObj.name, 'utf-8');
            } catch (err) {
                console.error('Error opening editor:', err);
            } finally {
                tmpObj.removeCallback();
            }
        }
    }
}
