import inquirer from 'inquirer';
import * as tmp from 'tmp';
import * as fs from 'fs';
import * as child_process from 'child_process';
import { getBranchDiff } from '../context/git';
import { getIntentContext } from '../services/intent-service';
import { buildContextPrompt } from '../services/prompt-builder';
import { getOpenAIClient, getModel } from '../ai/client';
import { calculateCost } from '../services/token-cost';

interface PROptions {
    tradeOffs?: boolean;
    aiAttribution?: boolean;
    dryRun?: boolean;
    context?: string;
}

export async function generatePRDescription(options: PROptions = { tradeOffs: true, aiAttribution: false }) {
    // 1. Get Branch Diff
    const diff = await getBranchDiff('main');
    if (!diff) {
        console.error('No changes found between HEAD and main.');
        return;
    }

    // 2. Get AI Context
    const context = await getIntentContext();

    // 3. Construct Prompt
    const promptContext = buildContextPrompt(context, options.context);

    // Adjust prompt based on options
    const tradeOffInstruction = options.tradeOffs !== false
        ? '## Trade-offs / Decisions\n(Extracted from Context)'
        : '';

    const attributionInstruction = options.aiAttribution
        ? 'Add a footer: "\n> Generated by Antigravity CLI"'
        : '';

    const systemPrompt = `
You are a senior developer's assistant. Your goal is to write a Pull Request description in Markdown.

Structure:
# Title (Feat/Fix: ...)

## Summary
(High level overview)

## Intent
(Clusters of changes using the provided Context)
- Refactor: ... because ...
- Fix: ... detected in ...

## Changes
(Bulleted list of technical changes)

${tradeOffInstruction}

${attributionInstruction}
`;

    const userPrompt = `
CONTEXT:
${promptContext}

DIFF:
${diff}

Generate the PR description.
`;

    console.log('Generating PR description...');

    // 4. Call AI
    let prDescription = '';
    try {
        const openai = getOpenAIClient();
        const completion = await openai.chat.completions.create({
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userPrompt }
            ],
            model: getModel(),
        });

        prDescription = completion.choices[0].message.content || '';
        const usage = (completion as any).usage;
        if (usage) {
            const cost = calculateCost(getModel(), usage);
            console.log(`Tokens used: ${usage.total_tokens} (Prompt: ${usage.prompt_tokens}, Completion: ${usage.completion_tokens})`);
            console.log(`Estimated cost: $${cost.toFixed(4)}`);
        }

    } catch (error: any) {
        console.error('Error generating PR description:', error.message);
        return;
    }

    if (options.dryRun) {
        console.log('\n--- Generated PR Description (Dry Run) ---\n');
        console.log(prDescription);
        return;
    }

    // 5. Interactive Loop
    while (true) {
        console.log('\n--- Draft PR Description ---\n');
        console.log(prDescription);
        console.log('\n----------------------------\n');

        const { action } = await inquirer.prompt([{
            type: 'list',
            name: 'action',
            message: 'What would you like to do?',
            choices: [
                { name: 'Finish (Exit)', value: 'finish' },
                { name: 'Edit (Open in Editor)', value: 'edit' },
                { name: 'Cancel', value: 'cancel' }
            ]
        }]);

        if (action === 'cancel') {
            console.log('Operation cancelled.');
            break;
        }

        if (action === 'finish') {
            console.log('Final output printed above.');
            break;
        }

        if (action === 'edit') {
            // Open editor
            const tmpObj = tmp.fileSync({ postfix: '.md' });
            fs.writeFileSync(tmpObj.name, prDescription);

            const editor = process.env.EDITOR || (process.platform === 'win32' ? 'notepad' : 'vi');

            try {
                console.log(`Opening ${editor}...`);
                child_process.execFileSync(editor, [tmpObj.name], { stdio: 'inherit' });
                prDescription = fs.readFileSync(tmpObj.name, 'utf-8');
            } catch (err) {
                console.error('Error opening editor:', err);
            } finally {
                tmpObj.removeCallback();
            }
        }
    }
}
